import { NextResponse } from 'next/server'

/**
 * Sirve firebase-messaging-sw.js con la config de Firebase inyectada.
 * Firebase Messaging busca este archivo en la raíz del dominio.
 */
export async function GET() {
  const rawConfig = process.env.NEXT_PUBLIC_FIREBASE_CONFIG || '{}'
  // Validar que es JSON parseable; si no, fallback a configuración por variables sueltas
  let config: Record<string, string>
  try {
    config = JSON.parse(rawConfig)
  } catch {
    config = {
      apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY || '',
      authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN || '',
      projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID || '',
      storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET || '',
      messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID || '',
      appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID || '',
    }
  }

  const body = `// Auto-generated by /firebase-messaging-sw.js route. Do not edit.
importScripts('https://www.gstatic.com/firebasejs/11.9.1/firebase-app-compat.js')
importScripts('https://www.gstatic.com/firebasejs/11.9.1/firebase-messaging-compat.js')

firebase.initializeApp(${JSON.stringify(config)})
const messaging = firebase.messaging()

messaging.onBackgroundMessage((payload) => {
  const title = (payload.notification && payload.notification.title) || 'Mi Granja'
  const options = {
    body: (payload.notification && payload.notification.body) || '',
    icon: '/icons/icon-192x192.png',
    badge: '/icons/icon-192x192.png',
    data: payload.data || {},
  }
  self.registration.showNotification(title, options)
})

self.addEventListener('notificationclick', (event) => {
  event.notification.close()
  const target = (event.notification.data && event.notification.data.url) || '/recordatorios'
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((list) => {
      for (const client of list) {
        if (client.url.includes(target) && 'focus' in client) return client.focus()
      }
      if (clients.openWindow) return clients.openWindow(target)
    }),
  )
})
`

  return new NextResponse(body, {
    status: 200,
    headers: {
      'Content-Type': 'application/javascript; charset=utf-8',
      'Cache-Control': 'public, max-age=0, must-revalidate',
      'Service-Worker-Allowed': '/',
    },
  })
}
