import { CURRENT_BACKUP_VERSION } from './backup-serialization'

// JSON.stringify keeps the copyable guide valid when descriptions contain newlines.
export const BACKUP_FORMAT = {
  _meta: {
    version: CURRENT_BACKUP_VERSION,
    exportDate: 'ISO 8601',
    farmId: 'string',
    farmName: 'string',
    exportedBy: 'string (userId)',
    counts: {
      animals: 0,
      animalRecords: 0,
      breedingRecords: 0,
      reminders: 0,
      farmInvitations: 0,
      sales: 0,
    },
  },
  _types: {
    animal: {
      id: 'string',
      farmerId: 'string (ID del usuario)',
      farmId: 'string (ID de la granja)',
      animalNumber: 'string (arete/identificador)',
      name: 'string (nombre opcional)',
      type: 'oveja | vaca | cabra | cerdo | gallina | perro | gato | equino | otro',
      gender: 'macho | hembra',
      breed: 'string (raza, opcional)',
      stage: 'cria | juvenil | engorda | reproductor | descarte',
      status: 'activo | muerto | vendido | perdido',
      statusAt: 'ISO 8601 (opcional, fecha del cambio de status)',
      statusNotes: 'string (notas sobre el cambio de status, opcional)',
      deathInfo:
        '{ reason: birth_defect | disease | injury | attack, date: ISO 8601, description: string } (si murió)',
      birthDate: 'ISO 8601 (opcional)',
      weight: 'number en gramos (opcional, ej: 4500 = 4.5kg)',
      age: 'number (edad en meses, opcional — se calcula desde birthDate)',
      motherId: 'string ID animal madre (opcional)',
      fatherId: 'string ID animal padre (opcional)',
      batch: 'string (lote, opcional)',
      currentAreaId: 'string | null (ID del área física actual dentro de la granja, opcional)',
      currentAreaAssignedAt: 'ISO 8601 | null (fecha de asignación al área actual, opcional)',
      notes: 'string (opcional)',
      isWeaned: 'true | false (opcional)',
      weanedAt: 'ISO 8601 (opcional)',
      weaningDestination: 'engorda | reproductor (destino al destetar, opcional)',
      soldInfo: '{ date, buyer?, weight? (gramos), price? (centavos) } (si vendido)',
      lostInfo: '{ lostAt, foundAt? } (si perdido)',
      records:
        "[{ id, type, category, title, date, weightGrams?, amountMl?, session?, severity?, isResolved?, resolvedDate?, treatment?, nextDueDate?, batch?, veterinarian?, cost?, notes?, appliedToAnimals?, isBulkApplication?, createdAt, createdBy, updatedAt? }] (type='weight' requiere weightGrams; type='milk' requiere amountMl y session)",
      customWeaningDays: 'number (override días de destete, opcional)',
      pregnantAt: 'ISO 8601 | null (fecha de confirmación de gestación, solo hembras)',
      pregnantBy: 'string | null (ID del macho que la preñó, solo hembras)',
      pregnantBreedingRecordId:
        'string | null (ID Firestore del empadre de la gestación activa, solo hembras)',
      pregnantBreedingId:
        'string | null (código legible del empadre, ej: 10-10-25-01, solo hembras)',
      birthedAt: 'ISO 8601 | null (fecha de parto como madre, solo hembras)',
      weanedMotherAt: 'ISO 8601 | null (fecha en que destetó sus crías, solo hembras)',
      lactationStatus: 'active | dry (estado explícito de lactancia, solo hembras)',
      lactationPurpose: 'offspring | dairy | dual (crías, leche o ambos)',
      driedAt: 'ISO 8601 | null (fecha en que terminó la lactancia)',
      availableToSaleAt:
        'ISO 8601 | null (marcado como listo para venta, se limpia al completarse la venta)',
      adminAction:
        '{ performedByAdmin, adminEmail?, adminId?, originalTimestamp, impersonationReason? } (opcional)',
      createdAt: 'ISO 8601',
      updatedAt: 'ISO 8601',
      imageUrl: 'string (URL de la foto principal, opcional)',
    },
    breedingRecord: {
      id: 'string',
      breedingId: 'string (ID legible, ej: 10-10-25-01, opcional)',
      farmerId: 'string',
      farmId: 'string',
      maleId: 'string (ID del animal macho)',
      breedingDate: 'ISO 8601 | null',
      femaleBreedingInfo:
        '[{ femaleId, pregnancyConfirmedDate?, expectedBirthDate?, actualBirthDate?, offspring?: string[] }]',
      status: 'active | finished (opcional, default: active)',
      notes: 'string (opcional)',
      comments: '[{ id, content, urgency?, createdAt? }] (opcional)',
      createdAt: 'ISO 8601',
      updatedAt: 'ISO 8601',
    },
    reminder: {
      id: 'string',
      farmerId: 'string',
      farmId: 'string',
      animalNumber: 'string arete (opcional, deprecated)',
      animalNumbers: '[string] aretes de animales asociados (opcional)',
      title: 'string',
      description: 'string',
      dueDate: 'ISO 8601',
      completed: 'true | false',
      completionByAnimal: '{ animalNumber: true/false } estado por animal (opcional)',
      priority: 'low | medium | high',
      type: 'medical | breeding | feeding | weight | other',
      assigneeIds: '[string] IDs de usuarios que reciben aviso (opcional)',
      notifiedAt: 'ISO 8601 último envío de digest (opcional)',
      lastOverdueNotifiedAt: 'ISO 8601 último escalado overdue 7d (opcional)',
      createdAt: 'ISO 8601',
      updatedAt: 'ISO 8601',
    },
    farmInvitation: {
      id: 'string',
      farmId: 'string',
      email: 'string',
      role: 'admin | manager | caretaker | veterinarian | viewer',
      permissions: '[{ module, actions[] }]',
      invitedBy: 'string',
      status: 'pending | accepted | rejected | expired | revoked',
      expiresAt: 'ISO 8601',
      createdAt: 'ISO 8601',
      updatedAt: 'ISO 8601',
    },
    farm: {
      id: 'string',
      name: 'string',
      description: 'string (opcional)',
      ownerId: 'string',
      location: '{ address?, city?, state?, country?, coordinates?: { lat, lng } } (opcional)',
      areas:
        "[{ id, name, description?, type, capacity?, layout?: { kind: 'rect'|'polygon', coordinateSystem: 'normalized', points: [{x,y}], color? }, isActive, notes?, createdAt, updatedAt }] (opcional)",
      createdAt: 'ISO 8601',
      updatedAt: 'ISO 8601',
    },
    sale: {
      id: 'string',
      farmId: 'string',
      farmerId: 'string',
      animals: '[{ animalId, animalNumber, weight? (gramos) }]',
      date: 'ISO 8601 (opcional)',
      pricePerKg: 'number centavos/kg (opcional)',
      priceType: 'en_pie | en_canal',
      buyer: 'string (opcional)',
      notes: 'string (opcional)',
      status: 'scheduled | pending | completed | cancelled',
      createdBy: 'string',
      updatedBy: 'string',
      createdAt: 'ISO 8601',
      updatedAt: 'ISO 8601',
    },
    _reglas_de_negocio: {
      _nota: 'Reglas que deben cumplirse para que los datos importados funcionen correctamente',
      campos_obligatorios_animal: 'id, animalNumber, type, stage, gender, createdAt, updatedAt',
      campos_nunca_undefined:
        'Firestore no acepta undefined. Omitir el campo por completo en vez de ponerlo como undefined.',
      peso_en_gramos: 'weight y soldInfo.price se almacenan en gramos y centavos respectivamente',
      fechas_iso_8601:
        'Todas las fechas deben estar en formato ISO 8601 (ej: 2026-03-17T00:00:00.000Z)',
      etapas_por_edad:
        'cria=no destetado, juvenil=destetado pero sin edad reproductiva, engorda=manual, reproductor=edad reproductiva alcanzada, descarte=manual',
      destete:
        'Al destetar una cría: isWeaned=true, weanedAt=fecha, stage cambia según destino. Para engorda→stage=engorda. Para reproductor→stage=juvenil.',
      nacimiento_muerto:
        'Si una cría nace muerta: status=muerto, statusAt=fecha del parto; deathInfo.reason puede ser birth_defect',
      estado_reproductivo:
        'Solo hembras. Gestación y lactancia pueden coexistir. lactationStatus=active mantiene Madre/Lechera; el destete sólo termina la lactancia cuando lactationPurpose=offspring.',
      ids_de_referencia:
        'motherId, fatherId, pregnantBy, pregnantBreedingRecordId, records[].appliedToAnimals, maleId, femaleId y offspring[] se remapean automáticamente.',
      peso_auto_sync:
        'records[] type=weight con weightGrams es la fuente de verdad. animal.weight conserva sólo el último valor como resumen.',
    },
  },
  farm: {},
  animals: [],
  breedingRecords: [],
  reminders: [],
  farmInvitations: [],
  sales: [],
}

export const BACKUP_SCHEMA_JSON = JSON.stringify(BACKUP_FORMAT, null, 2)
